version: '3.9'

services:
  app:
    build: app
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./app/src:/app/src
      - ./app/tsconfig.json:/app/tsconfig.json
      - ./app/astro.config.mjs:/app/astro.config.mjs
      - ./app/svelte.config.js:/app/svelte.config.js
      - ./app/tailwind.config.mjs:/app/tailwind.config.mjs
      - ./app/package.json:/app/package.json
      - .env:/app/.env
      - ./cdn:/app/public

volumes:
  db: